name: 'Andrew Lorente'
password_digest: '$2a$10$XcUFtgOUkAAZdNH7tkcMqOwE6Mrn00dcVHcqVxUCEHgO683ygxEsC'
preferred_compliment: 'handsome'
error_emails:
    host: 'smtp.sendgrid.net'
    sender: 'identity-errors@andrewlorente.com'
    recipients: ['identity-errors@andrewlorente.com']
