name: 'Erin Call'
passphrase_digest: '$2a$10$XcUFtgOUkAAZdNH7tkcMqOwE6Mrn00dcVHcqVxUCEHgO683ygxEsC'
preferred_compliment: 'cutie'
error_emails:
    host: 'smtp.sendgrid.net'
    sender: 'identity-errors@erincall.com'
    recipients: ['identity-errors@erincall.com']
